version: '3.8'

services:
  basian:
    image: rust_box:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8003:8080"
    volumes:
      - .:/workspace
    command: tail /dev/null
    deploy:
      resources:
        limits:
          cpus: '8'
          memory: 32G  # 32GBのメモリを制限として設定
        reservations:
          cpus: '1'
          memory: 512M  # 最低でも512MBのメモリを予約
